### PR TITLE
Live Content API 

### PR DESCRIPTION
**Pull request by rahulrvp**
This PR adds a new API to the SDK, `getLiveContent()`. This API is responsible for delivering live content based on the provided slot (campaign name).

Here is the sample code for using the `getLiveContent()` API.

```java
Blueshift
        .getInstance(mContext)
        .getLiveContent("Editors_Picks_Json", new LiveContentCallback() {
            @Override
            public void onReceive(String json) {
                // use the json and do stuff.
            }
        });
```

### CODE REVIEW

**Comment by nipunbhatia** [comment]
Would this support device id?

**Comment by rahulrvp** [comment]
No. This will only do a GET call on the /live API with slot, API key and email. The result will be delivered to ui thread using the onReceive method.

Ex: https://api.getblueshift.com/live?slot=Editors_Picks_Json&email=testuser@getblueshift.com&x=5dfe3c9aee8b375bcc616079b08156d9

**Comment by nipunbhatia** [comment]
Can we extend it to pass a key name to the method - email, or device_id or customer_id. based on the key name provided we construct the api call with key name and value as the parameter. Currently these keys are not supported by the API but in the future we might want to.

**Comment by rahulrvp** [comment]
Ok, we could have separate methods for separate keys. There are two ways of doing it. Either we could take ii internally from `UserInfo` and pre-loaded device parameters.

```java
// 1.
public void getLiveContentByEmail(String slot, Callback callback)
public void getLiveContentByDeviceId(String slot, Callback callback)
public void getLiveContentByCustomerId(String slot, Callback callback)
```
or we can let the developer pass the keys to the method.
```java
// 2.
public void getLiveContentByEmail(String email, String slot, Callback callback)
public void getLiveContentByDeviceId(String deviceId, String slot, Callback callback)
public void getLiveContentByCustomerId(String customerId, String slot, Callback callback)
```
Which one should we support?

**Comment by nipunbhatia** [comment]
Lets do 1

**Comment by rahulrvp** [comment]
## Update
The SDK now contains 3 APIs to load live content.

```java
/**
 * Note: Developer need to set the email inside `UserInfo` after sign in.
 * If not, the API will be called without email.
 */
Blueshift
        .getInstance(mContext)
        .getLiveContentByEmail("Editors_Picks_Json", new LiveContentCallback() {
            @Override
            public void onReceive(String json) {
                // use the json and do stuff.
            }
        });
```

```java
/**
 * Note: Developer need to set the retailer customer id inside `UserInfo` after sign in.
 * If not, the API will be called without email.
 */
Blueshift
        .getInstance(mContext)
        .getLiveContentByCustomerId("Editors_Picks_Json", new LiveContentCallback() {
            @Override
            public void onReceive(String json) {
                // use the json and do stuff.
            }
        });
```

```java
Blueshift
        .getInstance(mContext)
        .getLiveContentByDeviceId("Editors_Picks_Json", new LiveContentCallback() {
            @Override
            public void onReceive(String json) {
                // use the json and do stuff.
            }
        });
```

**Pull request merged**
